# -*- coding: utf-8 -*-
"""
원료 데이터베이스 (데모/샘플 데이터)
app.py 에서 `from raw_materials import DB` 로 사용됩니다.

각 항목 스키마:
{
    "id": str,            # 고유 ID
    "name": str,          # 원료명
    "inci": str,          # INCI명
    "cas": str,           # CAS No.
    "category": str,      # CATEGORIES 중 하나
    "status": str,        # "active" | "outofstock" | "discontinued"
    "price": int,         # 참고 단가 (원/kg)
    "desc": str,          # 설명
    "subs": [             # (선택) 추천 대체재 목록
        {"id": str, "match": "same" | "similar", "diff": str},
        ...
    ],
}
"""

DB = [
    # ------------------------------------------------------------------ 유화제
    {
        "id": "ceteareth20",
        "name": "Ceteareth-20",
        "inci": "Ceteareth-20",
        "cas": "68439-49-6",
        "category": "유화제",
        "status": "discontinued",
        "price": 9500,
        "desc": "폭넓게 쓰이던 PEG계 비이온성 O/W 유화제. 원료사 단종으로 대체재 검토가 필요합니다.",
        "subs": [
            {"id": "polysorbate60", "match": "same",
             "diff": "동일한 PEG계 비이온성 유화제 계열. HLB가 유사해 처방 치환이 비교적 쉽습니다."},
            {"id": "cetearylglucoside", "match": "similar",
             "diff": "PEG-free 천연유래 대체재. HLB가 낮아 보조 유화제 병용을 권장합니다."},
            {"id": "glycerylstearate", "match": "similar",
             "diff": "단독 사용 시 유화력이 약해 보조 유화제와 병용이 필요합니다."},
        ],
    },
    {
        "id": "cetearylalcohol",
        "name": "Cetearyl Alcohol",
        "inci": "Cetearyl Alcohol",
        "cas": "67762-27-0",
        "category": "유화제",
        "status": "active",
        "price": 6800,
        "desc": "지방알코올 계열의 보조 유화제 겸 점증 안정화제. 크림류 전반에 널리 사용됩니다.",
    },
    {
        "id": "glycerylstearate",
        "name": "Glyceryl Stearate",
        "inci": "Glyceryl Stearate",
        "cas": "31566-31-1",
        "category": "유화제",
        "status": "active",
        "price": 8200,
        "desc": "모노글리세라이드 계열 O/W 유화제. 단독 사용 시 유화력이 약해 보조 유화제와 조합해 사용합니다.",
    },
    {
        "id": "polysorbate60",
        "name": "Polysorbate 60",
        "inci": "Polysorbate 60",
        "cas": "9005-67-8",
        "category": "유화제",
        "status": "active",
        "price": 11500,
        "desc": "PEG계 비이온성 유화제로 Ceteareth 계열의 대표적인 대체 후보입니다.",
    },
    {
        "id": "cetearylglucoside",
        "name": "Cetearyl Glucoside",
        "inci": "Cetearyl Glucoside",
        "cas": "141464-42-4",
        "category": "유화제",
        "status": "active",
        "price": 15800,
        "desc": "PEG-free 천연유래 알킬글루코사이드계 유화제. 저자극 처방에 적합합니다.",
    },

    # ------------------------------------------------------------------ 점증제
    {
        "id": "acrylatescrosspolymer",
        "name": "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
        "inci": "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
        "cas": "977155-32-8",
        "category": "점증제",
        "status": "outofstock",
        "price": 32000,
        "desc": "고점도 발현이 우수한 아크릴레이트계 점증제. 현재 공급사 재고 부족 상태입니다.",
        "subs": [
            {"id": "carbomer", "match": "same",
             "diff": "동일 계열의 아크릴레이트 고분자 점증제. 중화제(TEA/NaOH)가 별도로 필요합니다."},
            {"id": "sclerotiumgum", "match": "similar",
             "diff": "천연 유래 점증제로 전해질 안정성이 우수하나, 점도 발현 pH 범위가 다릅니다."},
            {"id": "xanthangum", "match": "similar",
             "diff": "저점도 영역에서 텍스처가 다르며, 전해질에 대한 내성이 강합니다."},
        ],
    },
    {
        "id": "carbomer",
        "name": "Carbomer",
        "inci": "Carbomer",
        "cas": "9007-20-9",
        "category": "점증제",
        "status": "active",
        "price": 24500,
        "desc": "가교형 아크릴산 고분자 점증제. 중화 후 투명한 겔 texture를 형성합니다.",
    },
    {
        "id": "xanthangum",
        "name": "Xanthan Gum",
        "inci": "Xanthan Gum",
        "cas": "11138-66-2",
        "category": "점증제",
        "status": "active",
        "price": 13200,
        "desc": "미생물 발효 유래 천연 검류 점증제. 전해질 함유 처방에도 안정적입니다.",
    },
    {
        "id": "sclerotiumgum",
        "name": "Sclerotium Gum",
        "inci": "Sclerotium Gum",
        "cas": "895073-08-4",
        "category": "점증제",
        "status": "active",
        "price": 42000,
        "desc": "발효 유래 천연 점증제로 사용감이 가볍고 전해질 안정성이 우수합니다.",
    },
    {
        "id": "hec",
        "name": "Hydroxyethylcellulose",
        "inci": "Hydroxyethylcellulose",
        "cas": "9004-62-0",
        "category": "점증제",
        "status": "active",
        "price": 18700,
        "desc": "셀룰로오스 유도체 점증제. 계면활성제 함유 세정 제품에 자주 사용됩니다.",
    },

    # ------------------------------------------------------------------ 보습제
    {
        "id": "peg8",
        "name": "PEG-8",
        "inci": "PEG-8",
        "cas": "25322-68-3",
        "category": "보습제",
        "status": "discontinued",
        "price": 4200,
        "desc": "저분자 폴리에틸렌글리콜 보습제. 원료사 라인업 정리로 단종되었습니다.",
        "subs": [
            {"id": "butyleneglycol", "match": "similar",
             "diff": "PEG-free 보습제. 보습력은 유사하나 사용감이 더 가볍습니다."},
            {"id": "glycerin", "match": "similar",
             "diff": "가장 보편적인 대체 보습제. 끈적임이 다소 더 있을 수 있습니다."},
            {"id": "propanediol", "match": "similar",
             "diff": "PEG-free이며 방부 보조 기능도 있으나 단가가 더 높습니다."},
        ],
    },
    {
        "id": "glycerin",
        "name": "Glycerin",
        "inci": "Glycerin",
        "cas": "56-81-5",
        "category": "보습제",
        "status": "active",
        "price": 2100,
        "desc": "가장 대표적인 보습제. 다양한 제형에 폭넓게 사용됩니다.",
    },
    {
        "id": "butyleneglycol",
        "name": "Butylene Glycol",
        "inci": "Butylene Glycol",
        "cas": "107-88-0",
        "category": "보습제",
        "status": "active",
        "price": 3400,
        "desc": "가벼운 사용감의 다가알코올 보습제. 방부 보조 기능도 일부 있습니다.",
    },
    {
        "id": "propanediol",
        "name": "Propanediol",
        "inci": "Propanediol",
        "cas": "504-63-2",
        "category": "보습제",
        "status": "active",
        "price": 6900,
        "desc": "식물유래 1,3-프로판다이올. 보습과 동시에 방부 보조 효과가 있습니다.",
    },
    {
        "id": "sodiumhyaluronate",
        "name": "Sodium Hyaluronate",
        "inci": "Sodium Hyaluronate",
        "cas": "9067-32-7",
        "category": "보습제",
        "status": "active",
        "price": 185000,
        "desc": "고보습 기능성 원료로 소량 첨가로도 높은 보습 효과를 냅니다.",
    },

    # ------------------------------------------------------------------ 방부제
    {
        "id": "mit",
        "name": "Methylisothiazolinone",
        "inci": "Methylisothiazolinone",
        "cas": "2682-20-4",
        "category": "방부제",
        "status": "outofstock",
        "price": 28000,
        "desc": "이소치아졸리논계 방부제. 규제 강화 및 알러지 이슈로 재고 확보가 어렵습니다.",
        "subs": [
            {"id": "phenoxyethanol", "match": "similar",
             "diff": "광범위 항균 방부제. MIT 대비 알러지 이슈가 적으나 항진균력 보완이 필요합니다."},
            {"id": "hexanediol", "match": "similar",
             "diff": "저자극 다기능 방부 보조제. 방부력 보완을 위해 병용을 권장합니다."},
            {"id": "sodiumbenzoate", "match": "similar",
             "diff": "저pH 조건에서만 효과적이므로 제형 pH 확인이 필요합니다."},
        ],
    },
    {
        "id": "chlorphenesin",
        "name": "Chlorphenesin",
        "inci": "Chlorphenesin",
        "cas": "104-29-0",
        "category": "방부제",
        "status": "discontinued",
        "price": 22000,
        "desc": "페녹시 계열 방부제 겸 컨디셔닝제. 원료사 생산 중단으로 단종되었습니다.",
        "subs": [
            {"id": "phenoxyethanol", "match": "same",
             "diff": "유사한 항균 스펙트럼을 가진 동일 계열(페녹시)의 방부제입니다."},
            {"id": "ethylhexylglycerin", "match": "similar",
             "diff": "방부 보조 및 컨디셔닝 기능이 있으나 단독으로는 방부력이 부족합니다."},
        ],
    },
    {
        "id": "phenoxyethanol",
        "name": "Phenoxyethanol",
        "inci": "Phenoxyethanol",
        "cas": "122-99-6",
        "category": "방부제",
        "status": "active",
        "price": 9800,
        "desc": "가장 널리 쓰이는 광범위 항균 방부제입니다.",
    },
    {
        "id": "hexanediol",
        "name": "1,2-Hexanediol",
        "inci": "1,2-Hexanediol",
        "cas": "6920-22-5",
        "category": "방부제",
        "status": "active",
        "price": 15400,
        "desc": "저자극 다기능 방부 보조제. 보습 기능도 일부 있습니다.",
    },
    {
        "id": "sodiumbenzoate",
        "name": "Sodium Benzoate",
        "inci": "Sodium Benzoate",
        "cas": "532-32-1",
        "category": "방부제",
        "status": "active",
        "price": 4600,
        "desc": "저pH 처방에 적합한 안식향산계 방부제입니다.",
    },
    {
        "id": "ethylhexylglycerin",
        "name": "Ethylhexylglycerin",
        "inci": "Ethylhexylglycerin",
        "cas": "70445-33-9",
        "category": "방부제",
        "status": "active",
        "price": 26800,
        "desc": "방부 보조 및 피부 컨디셔닝 기능을 겸하는 원료입니다.",
    },

    # ------------------------------------------------------------------ 계면활성제
    {
        "id": "sles",
        "name": "Sodium Laureth Sulfate",
        "inci": "Sodium Laureth Sulfate",
        "cas": "9004-82-4",
        "category": "계면활성제",
        "status": "active",
        "price": 4300,
        "desc": "세정력이 우수한 음이온 계면활성제. 세안/바디 클렌저에 널리 사용됩니다.",
    },
    {
        "id": "capb",
        "name": "Cocamidopropyl Betaine",
        "inci": "Cocamidopropyl Betaine",
        "cas": "61789-40-0",
        "category": "계면활성제",
        "status": "active",
        "price": 6200,
        "desc": "양쪽성 계면활성제로 자극 완화 및 기포 보조 역할을 합니다.",
    },
    {
        "id": "decylglucoside",
        "name": "Decyl Glucoside",
        "inci": "Decyl Glucoside",
        "cas": "68515-73-1",
        "category": "계면활성제",
        "status": "active",
        "price": 9600,
        "desc": "저자극 천연유래 비이온성 계면활성제입니다.",
    },
    {
        "id": "sci",
        "name": "Sodium Cocoyl Isethionate",
        "inci": "Sodium Cocoyl Isethionate",
        "cas": "61789-32-0",
        "category": "계면활성제",
        "status": "active",
        "price": 12400,
        "desc": "부드러운 세정감을 주는 아미노산계 계면활성제. 고체 클렌저에 주로 사용됩니다.",
    },

    # ------------------------------------------------------------- 오일/에몰리언트
    {
        "id": "ccts",
        "name": "Caprylic/Capric Triglyceride",
        "inci": "Caprylic/Capric Triglyceride",
        "cas": "73398-61-5",
        "category": "오일/에몰리언트",
        "status": "active",
        "price": 8900,
        "desc": "산화 안정성이 우수한 에몰리언트 오일. 가볍고 산뜻한 사용감을 줍니다.",
    },
    {
        "id": "squalane",
        "name": "Squalane",
        "inci": "Squalane",
        "cas": "111-01-3",
        "category": "오일/에몰리언트",
        "status": "active",
        "price": 34000,
        "desc": "피부 친화적인 에몰리언트로 산화 안정성이 뛰어난 식물성 오일입니다.",
    },
    {
        "id": "ipm",
        "name": "Isopropyl Myristate",
        "inci": "Isopropyl Myristate",
        "cas": "110-27-0",
        "category": "오일/에몰리언트",
        "status": "active",
        "price": 7200,
        "desc": "흡수가 빠른 합성 에스테르 에몰리언트입니다.",
    },
    {
        "id": "jojobaoil",
        "name": "Jojoba Oil",
        "inci": "Simmondsia Chinensis (Jojoba) Seed Oil",
        "cas": "90045-98-0",
        "category": "오일/에몰리언트",
        "status": "active",
        "price": 28500,
        "desc": "피지와 유사한 조성의 왁스 에스테르 오일로 산화 안정성이 우수합니다.",
    },

    # ------------------------------------------------------------- 자외선차단제
    {
        "id": "emc",
        "name": "Ethylhexyl Methoxycinnamate",
        "inci": "Ethylhexyl Methoxycinnamate",
        "cas": "5466-77-3",
        "category": "자외선차단제",
        "status": "active",
        "price": 21400,
        "desc": "UVB를 흡수하는 유기 자외선차단 성분입니다.",
    },
    {
        "id": "tio2",
        "name": "Titanium Dioxide",
        "inci": "Titanium Dioxide",
        "cas": "13463-67-7",
        "category": "자외선차단제",
        "status": "active",
        "price": 32000,
        "desc": "무기 자외선차단제로 UVA/UVB를 산란·차단합니다.",
    },
    {
        "id": "zno",
        "name": "Zinc Oxide",
        "inci": "Zinc Oxide",
        "cas": "1314-13-2",
        "category": "자외선차단제",
        "status": "active",
        "price": 27800,
        "desc": "무기 자외선차단제. 넓은 파장대의 UVA/UVB를 차단합니다.",
    },
    {
        "id": "avobenzone",
        "name": "Butyl Methoxydibenzoylmethane",
        "inci": "Butyl Methoxydibenzoylmethane",
        "cas": "70356-09-1",
        "category": "자외선차단제",
        "status": "active",
        "price": 68000,
        "desc": "UVA를 폭넓게 흡수하는 유기 자외선차단 성분입니다.",
    },

    # ------------------------------------------------------------- 산화방지제
    {
        "id": "tocopherol",
        "name": "Tocopherol",
        "inci": "Tocopherol",
        "cas": "10191-41-0",
        "category": "산화방지제",
        "status": "active",
        "price": 42000,
        "desc": "비타민 E 유래 천연 산화방지제입니다.",
    },
    {
        "id": "bht",
        "name": "BHT",
        "inci": "BHT",
        "cas": "128-37-0",
        "category": "산화방지제",
        "status": "active",
        "price": 12800,
        "desc": "합성 산화방지제로 오일 및 유화 제품의 산패를 지연시킵니다.",
    },
    {
        "id": "ascorbylpalmitate",
        "name": "Ascorbyl Palmitate",
        "inci": "Ascorbyl Palmitate",
        "cas": "137-66-6",
        "category": "산화방지제",
        "status": "active",
        "price": 38500,
        "desc": "지용성 비타민C 유도체로 산화방지 및 컨디셔닝 기능을 겸합니다.",
    },

    # ------------------------------------------------------------------ 실리콘
    {
        "id": "dimethicone",
        "name": "Dimethicone",
        "inci": "Dimethicone",
        "cas": "9006-65-9",
        "category": "실리콘",
        "status": "active",
        "price": 16400,
        "desc": "가장 널리 쓰이는 실리콘 오일로 매끈한 사용감을 부여합니다.",
    },
    {
        "id": "cyclopentasiloxane",
        "name": "Cyclopentasiloxane",
        "inci": "Cyclopentasiloxane",
        "cas": "541-02-6",
        "category": "실리콘",
        "status": "active",
        "price": 22600,
        "desc": "휘발성 실리콘으로 산뜻하고 가벼운 사용감을 줍니다.",
    },
    {
        "id": "dimethiconol",
        "name": "Dimethiconol",
        "inci": "Dimethiconol",
        "cas": "31692-79-2",
        "category": "실리콘",
        "status": "active",
        "price": 24800,
        "desc": "고분자 실리콘으로 컨디셔닝 및 광택 부여에 사용됩니다.",
    },

    # ----------------------------------------------------------------- pH조절제
    {
        "id": "citricacid",
        "name": "Citric Acid",
        "inci": "Citric Acid",
        "cas": "77-92-9",
        "category": "pH조절제",
        "status": "active",
        "price": 3200,
        "desc": "천연유래 산성 pH 조절제. 제형의 pH를 낮추는 데 사용됩니다.",
    },
    {
        "id": "tea",
        "name": "Triethanolamine",
        "inci": "Triethanolamine",
        "cas": "102-71-6",
        "category": "pH조절제",
        "status": "active",
        "price": 5800,
        "desc": "카보머 등 산성 점증제의 중화제로 사용되는 알칼리성 pH 조절제입니다.",
    },
    {
        "id": "naoh",
        "name": "Sodium Hydroxide",
        "inci": "Sodium Hydroxide",
        "cas": "1310-73-2",
        "category": "pH조절제",
        "status": "active",
        "price": 1800,
        "desc": "강알칼리성 pH 조절제. 소량으로 강한 중화력을 가집니다.",
    },
    {
        "id": "lacticacid",
        "name": "Lactic Acid",
        "inci": "Lactic Acid",
        "cas": "50-21-5",
        "category": "pH조절제",
        "status": "active",
        "price": 4900,
        "desc": "AHA 계열 산으로 pH 조절과 각질 케어 기능을 겸합니다.",
    },
]
